---
# tasks file for db
- name: Set DB server name and IP variables
  ansible.builtin.set_fact:
    db_name: "{{ (hostvars | dict2items | selectattr('key', 'match', '^reddit-db.*') | list | first).key }}"
    db_ip: "{{ (hostvars | dict2items | selectattr('key', 'match', '^reddit-db.*') | list | first).value.ansible_host }}"
    # mongo_bind_ip: "{{ (hostvars | dict2items | selectattr('key', 'match', '^reddit-app.*') | list | first).value.internal_ip }}"

###### Debug task (can be commented)

# - name: Print db_hostname and db_ip
#   debug:
#     var: db_name,db_ip

# - name: Print local env
#   debug:
#     msg:
#      - "local env: {{ env }}"

###### "Usefull" task
- name: Change_mongo_configuration
  become: true
  ansible.builtin.template:
    src: ../templates/mongod.conf.j2                    # jinja file template
    dest: /etc/mongod.conf
    mode: "0644"
    owner: ubuntu
    group: ubuntu
                               # -rw-r--r-- mode for files, should be in ""
  notify: Restart_mongod_service
