---
- name: Install and configure docker
  hosts: all
  become: true
  vars:

  tasks:
    - name: Update.apt
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - gnupg-agent
        - python3-pip
        - virtualenv
        - python3-setuptools

    - name: Install.GPG
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
        force: true

    - name: Install.Repo
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: true

    - name: Docker.install
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    - name: Added to the docker group.
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true

    - name: Reset ssh connection to apply user changes.
      ansible.builtin.meta: reset_connection
...
